FROM node:lts-alpine3.12 as build

# RUN echo 
# RUN npm config set registry https://registry.npm.taobao.org

WORKDIR /tmp/cache

ADD test.text /temp/cache
# ADD package.json .
# ADD package-lock.json .
# RUN npm install

# ADD . .
# RUN npm run build

#FROM socialengine/nginx-spa:latest as nginx

# COPY --from=build /tmp/cache /app